# Generated by Django 3.2.10 on 2022-01-01 17:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=128)),
                ('last_name', models.TextField(max_length=128)),
                ('address_1', models.TextField(max_length=128)),
                ('address_2', models.TextField(max_length=128)),
                ('city', models.TextField(max_length=128)),
                ('state', models.TextField(max_length=2)),
                ('zip_code', models.TextField(max_length=5)),
                ('country', models.TextField(max_length=128, validators=[api.models.validate_country])),
                ('ssn', models.TextField(max_length=9)),
                ('email_address', models.TextField(max_length=128)),
                ('dob', models.TextField(max_length=10, validators=[api.models.validate_dob])),
            ],
        ),
    ]
