# Generated by Django 3.2.10 on 2022-01-01 18:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='address_2',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='state',
            field=models.TextField(max_length=2, validators=[api.models.validate_state]),
        ),
        migrations.AlterField(
            model_name='signupform',
            name='zip_code',
            field=models.TextField(max_length=5, validators=[api.models.validate_zip_code]),
        ),
    ]
